### ISSUE TITLE
Received FAILURE signal : When Creating Ec2Intance

### ISSUE THREAD

**Issue by gwasky** [caktus/aws-web-stacks#59]
Been at this for hours.

Trying to use the dokku template, but it keeps failing when creating an ec2 instance, then rolls back
My default region is us-east-2. 

I have changed the AMI id to a Ubuntu AMI for us-east-2, it still wont go past the create ec2 instance.

Any pointers here?

**Comment by gwasky** [comment]
How do u troubleshoot this?
![cfstack](https://user-images.githubusercontent.com/13219355/54480707-c57c3500-483c-11e9-8284-293cfcf665ab.png)

**Comment by gwasky** [comment]
Disabled rollback to keep, dokku( **v0.13.1**) installation seems to fail. Returns the error below:

> 2019-03-16 20:52:56,118 [ERROR] Command 02_install (sudo -E bash bootstrap.sh) failed
> 2019-03-16 20:52:56,118 [ERROR] Error encountered during build of install_dokku: Command 02_install failed
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
>     CloudFormationCarpenter(config, self._auth_config).build(worklog)
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
>     changes['commands'] = CommandTool().apply(self._config.commands)
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
>     raise ToolError(u"Command %s failed" % name)
> ToolError: Command 02_install failed
> 2019-03-16 20:52:56,122 [ERROR] -----------------------BUILD FAILED!------------------------
> 2019-03-16 20:52:56,127 [ERROR] Unhandled exception during build: Command 02_install failed
> Traceback (most recent call last):
>   File "/usr/local/bin/cfn-init", line 171, in <module>
>     worklog.build(metadata, configSets)
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
>     Contractor(metadata).build(configSets, self)
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
>     self.run_config(config, worklog)
>   File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
>     CloudFormationCarpenter(config, self._auth_config).build(worklog)
>  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
>    changes['commands'] = CommandTool().apply(self._config.commands)
>  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
>     raise ToolError(u"Command %s failed" % name)
> ToolError: Command 02_install failed
